highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://ja9yoonkim.github.io
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: #/vitae/
title: Jae-Yoon Kim
name: Jae-Yoon Kim
email: jaeyoonk@xjtu.edu.cn
email_full: mailto:jaeyoonk@xjtu.edu.cn
website: #github.io/sustain
website_full: #https://jekyllt.github.io/sustain
github: ja9yoonkim
twitter: twitter
tel: #+44 0000 000000
tel_full: #tel:+440000000000
google_maps: 'https://maps.app.goo.gl/5HWidzJuupE2egoo6'
address:
  street1: Xian’ning West Road 28
  city: Xi'an, Shaanxi Province
  postcode: 710049
  country: 710049, China
google_analytics: #UA-69300817-1
scholar_userid: S9clcowAAAAJ
ssrn_id: 2643520

# needed for travis-ci build
exclude: [vendor]
#Xian’ning West Road 28,Xi’an,Shaanxi Province,710049,P.R.China
